import turtle
t=turtle.Turtle()
s=turtle.Screen()
s.bgcolor('black')
t.color('red')
t.begin_fill()
t.fillcolor('red')
t.width(12)
t.left(140)
t.forward(180)
t.circle(-90,200)
#t.left(120)
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.hideturtle()
t.penup()
t.goto(0,300)
t.color('black')
t.pendown()
for i in range (5):
    t.left(75)
    t.forward(40)
    t.right(65)
    t.forward(45)
t.exitonclick()