import turtle 
t=turtle.Turtle()
turtle.title('heart shape')

t.color('red')
t.begin_fill()
t.fillcolor('red')
s=turtle.Screen()
s.bgcolor('black')
t.left(140)          
t.forward(180)       
t.circle(-90,200)         
t.left(120)          
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.hideturtle()
t.end_fill()
turtle.exitonclick()